import p1_img from "./bois blanc.png";
import p2_img from "./boiserie.jpg";
import p3_img from "./brique.jpg";
import p4_img from "./ceramique.jpg";
import p5_img from "./ciment_lafarge.jpg";
import p6_img from "./ciment.jpeg";
import p7_img from "./etanchiete.jpg";
import p8_img from "./tubes_ferronnerie.jpg";
import p9_img from "./gravier.jpg";
import p10_img from "./platre.jpg";
import p11_img from "./pvc_siphon.jpeg";
import p12_img from "./pvc_tuyaux.jpg";
import p13_img from "./sable.jpg";
import p14_img from "./sanitaires.jpeg";
import p15_img from "./tubes_ferronnerie.jpg";
import p16_img from "./tuiles.jpg";


let all_products = [
  {
    id: 1,
    name: "Brique 8 Trous",
    category: "blocs",
    image: p3_img,
    new_price: 50,
    old_price: 80,
  },
  {
    id: 2,
    name: "Briques 5 Trous",
    category: "blocs",
    image: p3_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 3,
    name: "Briques 3 Trous",
    category: "blocs",
    image: p3_img,
    new_price: 60,
    old_price: 100,
  },
  {
    id: 4,
    name: "Briques 9 Trous",
    category: "blocs",
    image: p3_img,
    new_price: 100,
    old_price: 150,
  },
  {
    id: 5,
    name: "Tuiles",
    category: "blocs",
    image: p16_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 6,
    name: "Faitiéres",
    category: "blocs",
    image: p3_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 7,
    name: "Sable Bousaada",
    category: "agregats",
    image: p13_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 8,
    name: "Sable Oued-Souf",
    category: "agregats",
    image: p13_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 9,
    name: "Sable Carriere o3",
    category: "agregats",
    image: p13_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 10,
    name: "Gravier 8/15",
    category: "agregats",
    image: p9_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 11,
    name: "Gravier 3/8",
    category: "agregats",
    image: p9_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 12,
    name: "Ciment Lafarge Chamil (25 et 50 kg)",
    category: "poudre",
    image: p5_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 13,
    name: "Ciment Lafarge Matine (25 et 50 kg)",
    category: "poudre",
    image: p5_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 14,
    name: "Ciment prompt (Vicat) (25 kg)",
    category: "poudre",
    image: p6_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 15,
    name: "Ciment blanc (25 et 50 kg)",
    category: "poudre",
    image: p6_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 16,
    name: "Ciment colle (25 kg ; Toutes marques)",
    category: "poudre",
    image: p6_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 17,
    name: "Platre Fleurus",
    category: "poudre",
    image: p10_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 18,
    name: "Platre AJIBA",
    category: "poudre",
    image: p10_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 19,
    name: "Roseaux",
    category: "poudre",
    image: p10_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 20,
    name: "Planches (toutes dimensions)",
    category: "coffrage",
    image: p1_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 21,
    name: "Madriers (toutes dimensions)",
    category: "coffrage",
    image: p1_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 22,
    name: "Demi-Madriers (toutes dimensions)",
    category: "coffrage",
    image: p1_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 23,
    name: "Chevron (toutes dimensions)",
    category: "coffrage",
    image: p1_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 24,
    name: "Liteau (toutes dimensions)",
    category: "coffrage",
    image: p1_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 25,
    name: "Fer a béton (differents diamètres)",
    category: "aciers",
    image: p8_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 26,
    name: "Fenetres (différentes dimensions)",
    category: "coffrage",
    image: p2_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 27,
    name: "Portes contre-plaquee (différentes dimensions)",
    category: "coffrage",
    image: p2_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 28,
    name: "Vasistas (différentes dimensions)",
    category: "coffrage",
    image: p2_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 29,
    name: "Variété de faiences et dalle de sol (différentes couleurs)",
    category: "ceramique",
    image: p4_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 30,
    name: "Plinthes (différentes couleurs)",
    category: "ceramique",
    image: p4_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 31,
    name: "Rouleau Pax (30, 40)",
    category: "coffrage",
    image: p7_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 32,
    name: "Rouleau Feutre (30, 40)",
    category: "coffrage",
    image: p7_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 33,
    name: "Bitume",
    category: "coffrage",
    image: p7_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 34,
    name: "Flinkot",
    category: "coffrage",
    image: p7_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 35,
    name: "Tuyaux PVC (différents diamètres)",
    category: "sanitaire",
    image: p12_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 36,
    name: "Siphons de Cours (différents diamètres)",
    category: "sanitaire",
    image: p12_img,
    new_price: 85,
    old_price: 120,
  },{
    id: 37,
    name: "Colle PVC",
    category: "sanitaire",
    image: p11_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 38,
    name: "Accessoires PVC",
    category: "sanitaire",
    image: p11_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 39,
    name: "Cuvettes anglaises",
    category: "sanitaire",
    image: p14_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 40,
    name: "Cuvettes turques",
    category: "sanitaire",
    image: p14_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 41,
    name: "Lavabo + pieds",
    category: "sanitaire",
    image: p14_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 42,
    name: "Lave-main",
    category: "sanitaire",
    image: p14_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 43,
    name: "Receveur de douche",
    category: "sanitaire",
    image: p14_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 44,
    name: "Eviers de cuisines",
    category: "sanitaire",
    image: p14_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 45,
    name: "Cornières (toutes dimensions)",
    category: "aciers",
    image: p15_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 46,
    name: "Tubes carrés",
    category: "aciers",
    image: p15_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 47,
    name: "Tubes Ronds",
    category: "aciers",
    image: p15_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 48,
    name: "Tubes Rectangle",
    category: "aciers",
    image: p15_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 49,
    name: "Fer Carré",
    category: "aciers",
    image: p15_img,
    new_price: 85,
    old_price: 120,
  },
  {
    id: 45,
    name: "Fer Rond",
    category: "aciers",
    image: p15_img,
    new_price: 85,
    old_price: 120,
  },
];

export default all_products;